# Generated by Django 3.2.8 on 2021-10-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0002_remove_topicinfo_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinfo',
            name='Character_Name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
