# Generated by Django 3.2.8 on 2021-10-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0003_topicinfo_character_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicinfo',
            old_name='Character_Name',
            new_name='Character_name',
        ),
    ]
