# Generated by Django 3.2.8 on 2021-10-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeApp', '0004_rename_character_name_topicinfo_character_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicinfo',
            old_name='Anime_Name',
            new_name='anime',
        ),
        migrations.RenameField(
            model_name='topicinfo',
            old_name='Character_name',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='topicinfo',
            old_name='Quotes',
            new_name='quote',
        ),
    ]
